version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=recipest_docker
      - POSTGRES_USER=recipest_docker
      - POSTGRES_PASSWORD=recipest_docker
    ports:
      - 5433:5432
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
